### ISSUE TITLE
[WORKAROUND] Convert 2.2 and 2.4 to 2.3 UTF-16

### ISSUE THREAD

**Issue by sergeevabc** [squell/id3#12]
Dear Marc, how to do that?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by squell** [comment]
Sorry, I have a pretty busy schedule these days, and writing proper answers takes a lot of time :)

1) For converting tags:
     - ID3v2.4 gets converted to ID3v2.3 automatically if you change _anything_ in the tag, e.g.
       `id3 -2 --update file.mp3` will work, for instance.
     - To convert ID3v2.2, it is necessary to clear the existing tag and write a brand new one; otherwise ID3 will write a v2.2 tag. You can get this behaviour by using instead:
        `id3 -2 --delete --update file.mp3`
    
        _But_ be aware that this last command will remove all non-standard frames. In case you want to keep those, you will have to copy these explicitly to the new tag, by using, for example:
        `id3 -2 --delete --update -wTPUB '%{TPB}'`
          which will fill the (v2.3) TPUB frame with the contents of the old (v2.2) TPB frame, which contains the "Publisher" field (which is not ordinarily used).

2) You cannot force id3 out-of-the-box to use UTF16 encoding --- it will choose to use ISO-8859-1 if this encoding can represent all characters, UTF16 otherwise. If you really want, for some reason, to _force_ UTF16, you can patch the source code. Replace the line in file `setid3v2.cpp` at [this location](https://github.com/squell/id3/blob/master/setid3v2.cpp#L190) with:
     ```c++
    data = char(true);
     ```
     After this, a simple recompile should work.

I hope this helps.
